name: Password-Manager


on:
  push:
    branches:
      - main


jobs:
  run-tests:
    name: Run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyopenssl --upgrade
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pytest

      - name: Archive Pytest test report
        uses: actions/upload-artifact@v3
        with:
          name: SuperTest-test-report
          path: report

      - name: Upload Pytest report to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: Pytest-test-report
          path: report
  lint:
    needs: run-tests
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: tonybajan/flake8-check-action@v1.3.0
      with:
        select: E3,E4,E5,E7,W6,F,B,G0
        maxlinelength: 200
        repotoken: ${{ secrets.GITHUB_TOKEN }}
